{
    'name': 'Gestión de Graduaciones de Pacientes',
    'version': '1.0',
    'category': 'Healthcare',
    'summary': 'Módulo para gestión de graduaciones oftalmológicas y cotizador',
    'author': 'Christian torres peewee',
    'depends': ['base', 'web', 'mail', 'product', 'sale'],
    'data': [
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/series_rx_data.xml',
        'views/graduacion_view.xml',
        'views/laboratorio_views.xml',
        'views/serie_rx_views.xml',
        'views/product_views.xml',
        'views/cotizador_views.xml',
        'views/menu_views.xml',
        'report/graduacion_report.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
